import Providers from "./Providers";
import type { Metadata } from 'next';
import "./globals.css";
import localFont from 'next/font/local'

export const metadata: Metadata = {
    title: 'سامانه فکر',
    description: 'Generated by create next app',

};

const Vazir = localFont({
  src: "../assets/Fonts/Vazir-FD-WOL.woff2",
  weight: '400'
})

// Root layout wraps content with Providers
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={` ${Vazir.className}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}

